version: '3.7'
services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_ADMIN_PASSWORD: "admin"
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath_dev/superset_config.py
